package org.cookiesturnier.corina.enums;

public enum Gamemode {

    BEDWARS,
    BEDWARS_CLASSIC,
    COOKIES,
    SKYWARS,
    QUICK_BEDWARS,
    CORES,
    RAGEMODE,
    TTT,
    AURA_CLASSIC,
    QUICKSURVIVALGAMES,
    SURVIVALGAMES24,
    AURAPLUS,
    CONQUEST,
    ZOMBIES,
    GUNGAME,
    ENDERGAMES,
    EXTREME_SURVIVALGAMES,
    HARDCORE,
    JUMPLEAGUE,
    MOLECRAFT,
    SPEEDUHC,
    MASTERBUILDERS,
    SKYUHC,
    PARTYGAMES,
    DEADBYDAYLIGHT,
    GUESSIT,
    BATTLEWALLS,
    CRYSTALWARS,
    SKYWARS116,
    MASTERBUILDERS116;

}
